/*
 * VibeIsland (DynamicIsland)
 * Copyright (C) 2024-2026 VibeIsland Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

import AppKit

/// Pasteboard vocabulary for the clipboard manager: which types are recorded,
/// which mean "do not record", and the marker we stamp on our own writes.
///
/// The ignore lists follow the `org.nspasteboard.*` convention documented at
/// <http://nspasteboard.org> plus the app-specific opt-outs password managers
/// use. Getting these wrong means a password manager's clipboard ends up in a
/// searchable history on disk, so they are treated as a hard requirement, not a
/// nicety.
enum ClipboardPasteboard {
    /// Content types the monitor knows how to store and restore.
    static let supportedTypes: [NSPasteboard.PasteboardType] = [
        .fileURL,
        .html,
        .png,
        .rtf,
        .string,
        .tiff
    ]

    static var defaultEnabledTypes: Set<String> {
        Set(supportedTypes.map(\.rawValue))
    }

    /// Presence of any of these on the pasteboard means the copy is explicitly
    /// not for clipboard managers: concealed (passwords), transient (internal
    /// hand-off), or auto-generated (produced without a user gesture).
    static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        // App-specific opt-outs that predate the convention above.
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "net.antelle.keeweb",
        "com.agilebits.onepassword"
    ]

    /// Editor/browser bookkeeping that rides along with a copy. Recording it
    /// would bloat the store, and — more importantly — diffing on it makes the
    /// same visible text look like a different item each time it is copied.
    static let metadataTypes: Set<String> = [
        "com.apple.notes.richtext",
        "com.apple.WebKit.custom-pasteboard-data",
        "org.chromium.web-custom-data",
        "org.chromium.source-url",
        "org.chromium.internal.source-token",
        "com.apple.cocoa.pasteboard.find",
        "public.url-name",
        clipboardManagerMarker.rawValue
    ]

    /// Stamped on the pasteboard when *we* write an entry back, so the poll that
    /// follows recognizes its own echo instead of recording a duplicate.
    static let clipboardManagerMarker = NSPasteboard.PasteboardType("com.zaaacqwq.VibeIsland.clipboard.self")

    /// Types dropped when pasting "without formatting" — the plain string is
    /// kept and every styled representation is discarded.
    static let formattingTypes: Set<String> = [
        NSPasteboard.PasteboardType.rtf.rawValue,
        NSPasteboard.PasteboardType.html.rawValue,
        "public.rtf",
        "public.html",
        "com.apple.flat-rtfd",
        "NeXT Rich Text Format v1.0 pasteboard type",
        "NeXT RTFD pasteboard type"
    ]

    /// File extension used for a blob of the given pasteboard type, so blobs on
    /// disk stay recognizable when inspected by hand.
    static func blobExtension(for type: String) -> String {
        switch type {
        case NSPasteboard.PasteboardType.png.rawValue: return "png"
        case NSPasteboard.PasteboardType.tiff.rawValue: return "tiff"
        case NSPasteboard.PasteboardType.rtf.rawValue: return "rtf"
        case NSPasteboard.PasteboardType.html.rawValue: return "html"
        case NSPasteboard.PasteboardType.fileURL.rawValue: return "fileurl"
        case NSPasteboard.PasteboardType.string.rawValue: return "txt"
        default: return "bin"
        }
    }
}
