import AppKit
import XCTest
@testable import VibeIsland

/// Capture rules for the clipboard manager. These are the decisions that decide
/// whether something private ends up on disk, so they are pinned by tests
/// rather than left to manual verification.
final class ClipboardCaptureTests: XCTestCase {
    private let enabledTypes = ClipboardPasteboard.defaultEnabledTypes
    private let maxBytes = 20 * 1024 * 1024

    private func stringRepresentation(_ text: String) -> [String: Data] {
        [NSPasteboard.PasteboardType.string.rawValue: Data(text.utf8)]
    }

    private func capture(_ representations: [[String: Data]]) -> ClipboardCapture.Result? {
        ClipboardCapture.makeItem(
            representations: representations,
            enabledTypes: enabledTypes,
            maxItemBytes: maxBytes
        )
    }

    // MARK: - Opt-outs

    func testConcealedCopyIsNotRecorded() throws {
        var representation = stringRepresentation("hunter2")
        representation["org.nspasteboard.ConcealedType"] = Data()

        XCTAssertNil(capture([representation]), "A password manager's concealed copy must never be stored")
    }

    func testTransientAndAutoGeneratedCopiesAreNotRecorded() throws {
        for optOut in ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"] {
            var representation = stringRepresentation("temp")
            representation[optOut] = Data()
            XCTAssertNil(capture([representation]), "\(optOut) must be honored")
        }
    }

    func testOwnWriteBackIsNotRecorded() throws {
        var representation = stringRepresentation("from history")
        representation[ClipboardPasteboard.clipboardManagerMarker.rawValue] = Data()

        XCTAssertNil(capture([representation]), "Our own pasteboard write must not be re-recorded")
    }

    func testDisabledTypeIsSkipped() throws {
        let result = ClipboardCapture.makeItem(
            representations: [stringRepresentation("plain text")],
            enabledTypes: [NSPasteboard.PasteboardType.png.rawValue],
            maxItemBytes: maxBytes
        )

        XCTAssertNil(result, "With .string disabled there is nothing left to record")
    }

    func testOversizedCopyIsSkipped() throws {
        let representation = [NSPasteboard.PasteboardType.png.rawValue: Data(count: 2_048)]

        let result = ClipboardCapture.makeItem(
            representations: [representation],
            enabledTypes: enabledTypes,
            maxItemBytes: 1_024
        )

        XCTAssertNil(result)
    }

    func testWhitespaceOnlyTextIsSkipped() throws {
        XCTAssertNil(capture([stringRepresentation("   \n\t  ")]))
    }

    // MARK: - Kinds

    func testPlainTextCapture() throws {
        let result = try XCTUnwrap(capture([stringRepresentation("  hello world  ")]))

        XCTAssertEqual(result.item.kind, .text)
        XCTAssertEqual(result.item.title, "hello world", "Preview titles are trimmed")
        XCTAssertEqual(result.item.numberOfCopies, 1)
        XCTAssertFalse(result.item.isPinned)
    }

    func testLongTextIsTruncatedForThePreview() throws {
        let long = String(repeating: "a", count: ClipboardCapture.maxTitleLength + 500)
        let result = try XCTUnwrap(capture([stringRepresentation(long)]))

        XCTAssertEqual(result.item.title.count, ClipboardCapture.maxTitleLength)
        XCTAssertEqual(
            result.values[NSPasteboard.PasteboardType.string.rawValue]?.count,
            long.utf8.count,
            "Truncation is for display only — the stored payload keeps every byte"
        )
    }

    func testImageOnlyCopyIsAnImage() throws {
        let representation = [NSPasteboard.PasteboardType.tiff.rawValue: Data(repeating: 0x1, count: 64)]
        let result = try XCTUnwrap(capture([representation]))

        XCTAssertEqual(result.item.kind, .image)
        XCTAssertTrue(result.item.title.isEmpty)
    }

    func testRichTextCarryingAnImageRenditionStaysText() throws {
        var representation = stringRepresentation("Formatted paragraph")
        representation[NSPasteboard.PasteboardType.rtf.rawValue] = Data(repeating: 0x2, count: 32)
        representation[NSPasteboard.PasteboardType.tiff.rawValue] = Data(repeating: 0x3, count: 32)

        let result = try XCTUnwrap(capture([representation]))

        XCTAssertEqual(result.item.kind, .text, "A text copy that also carries a rendition is still text")
        XCTAssertEqual(result.item.title, "Formatted paragraph")
    }

    func testMultipleFilesCollapseIntoOneEntry() throws {
        let first = "file:///Users/test/one.png"
        let second = "file:///Users/test/two.pdf"
        let representations = [first, second].map {
            [NSPasteboard.PasteboardType.fileURL.rawValue: Data($0.utf8)]
        }

        let result = try XCTUnwrap(capture(representations))

        XCTAssertEqual(result.item.kind, .file)
        XCTAssertEqual(result.item.fileNames, ["one.png", "two.pdf"])
        XCTAssertEqual(result.item.title, "one.png, two.pdf")
        XCTAssertEqual(
            result.item.payloads.filter { $0.type == NSPasteboard.PasteboardType.fileURL.rawValue }.count,
            1,
            "A multi-file copy is one history row, not one per file"
        )
        let joined = try XCTUnwrap(result.values[NSPasteboard.PasteboardType.fileURL.rawValue])
        XCTAssertEqual(String(data: joined, encoding: .utf8), "\(first)\n\(second)")
    }

    // MARK: - Payload storage

    func testSmallPayloadsStayInline() throws {
        let result = try XCTUnwrap(capture([stringRepresentation("short")]))
        let payload = try XCTUnwrap(result.item.payloads.first)

        XCTAssertNotNil(payload.inlineValue)
        XCTAssertNil(payload.blobFileName)
        XCTAssertFalse(payload.isBlobBacked)
    }

    func testLargePayloadsBecomeBlobs() throws {
        let big = Data(repeating: 0x7, count: ClipboardPayload.inlineByteLimit + 1)
        let result = try XCTUnwrap(capture([[NSPasteboard.PasteboardType.png.rawValue: big]]))
        let payload = try XCTUnwrap(result.item.payloads.first)

        XCTAssertTrue(payload.isBlobBacked)
        XCTAssertNil(payload.inlineValue, "Blob-backed payloads must not also inline their bytes")
        XCTAssertEqual(payload.byteCount, big.count)
    }

    // MARK: - De-duplication

    func testSameTextIsRecognizedAsTheSameContent() throws {
        let first = try XCTUnwrap(capture([stringRepresentation("repeat me")])).item
        let second = try XCTUnwrap(capture([stringRepresentation("repeat me")])).item

        XCTAssertNotEqual(first.id, second.id)
        XCTAssertTrue(first.hasSameContent(as: second))
    }

    func testEditorMetadataDoesNotDefeatDeDuplication() throws {
        var withMetadata = stringRepresentation("copy from browser")
        withMetadata["org.chromium.source-url"] = Data("https://example.com/a".utf8)
        var withDifferentMetadata = stringRepresentation("copy from browser")
        withDifferentMetadata["org.chromium.source-url"] = Data("https://example.com/b".utf8)

        let first = try XCTUnwrap(capture([withMetadata])).item
        let second = try XCTUnwrap(capture([withDifferentMetadata])).item

        XCTAssertTrue(
            first.hasSameContent(as: second),
            "The same visible text copied twice from different pages is one entry"
        )
    }

    func testDifferentTextIsNotTheSameContent() throws {
        let first = try XCTUnwrap(capture([stringRepresentation("one")])).item
        let second = try XCTUnwrap(capture([stringRepresentation("two")])).item

        XCTAssertFalse(first.hasSameContent(as: second))
    }

    func testRecopiedBumpsRecencyAndCount() throws {
        let original = try XCTUnwrap(capture([stringRepresentation("bump me")])).item
        let later = Date(timeIntervalSinceNow: 60)

        let bumped = original.recopied(at: later, sourceAppBundleID: "com.apple.Safari", sourceAppName: "Safari")

        XCTAssertEqual(bumped.numberOfCopies, 2)
        XCTAssertEqual(bumped.lastCopiedAt, later)
        XCTAssertEqual(bumped.firstCopiedAt, original.firstCopiedAt, "The first-copied stamp is history, not state")
        XCTAssertEqual(bumped.sourceAppBundleID, "com.apple.Safari")
    }

    // MARK: - Search

    func testSearchMatchesTitleFileNamesAndSourceApp() throws {
        var item = try XCTUnwrap(capture([stringRepresentation("Quarterly report")])).item
        item.sourceAppName = "Numbers"
        item.fileNames = ["summary.pdf"]

        XCTAssertTrue(item.matches("quarterly"))
        XCTAssertTrue(item.matches("summary.pdf"))
        XCTAssertTrue(item.matches("numbers"))
        XCTAssertTrue(item.matches("  "), "A blank query matches everything")
        XCTAssertFalse(item.matches("nonexistent"))
    }
}
